"""
=============================================================================
AR Features Builder — Period-based Mount Wilson Complexity Features
=============================================================================
Builds aggregated features (annual, monthly, weekly) from the
`mount_wilson_dataset.csv` dataset generated by `noaa_mount_wilson.py`.

For each period, every active region (AR) is represented once, using its
*peak* complexity within that period — this avoids double-counting regions
that have multiple daily observations.
=============================================================================
"""

import argparse
import csv
from pathlib import Path

import numpy as np
import pandas as pd

# ---------------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------------

DEFAULT_CSV_IN = "mount_wilson_dataset.csv"

THRESH_EPHEMERAL = 1   # persistence_days <= 1  → ephemeral
THRESH_LARGE     = 7   # persistence_days >= 7  → large (2-6 days → small)
HIGH_COMPLEXITY  = 4   # complexity >= 4: βγ, γ, βγδ, γδ


# as zero-filled rows instead of being missing.
DEFAULT_START_DATE = "1996-01"
DEFAULT_END_DATE   = "2026-02"


# ---------------------------------------------------------------------------
# Data loading 
# ---------------------------------------------------------------------------

def load_dataset(csv_in: str) -> pd.DataFrame:
    """Loads mount_wilson_dataset.csv and enriches it with per-region
    persistence, size classification, and complexity-related fields."""
    df = pd.read_csv(csv_in)
    df["date"] = pd.to_datetime(df["date"])

    # Global persistence of each active region (days it appears in the dataset)
    lifetime = (
        df.groupby("noaa_number")["date"]
        .agg(lambda x: (x.max() - x.min()).days + 1)
        .rename("persistence_days")
    )
    df = df.merge(lifetime, on="noaa_number")

    df["size_class"]   = df["persistence_days"].apply(classify_size)
    df["high_compl"]   = df["complexity"] >= HIGH_COMPLEXITY
    df["compl_x_area"] = df["complexity"] * df["area"]

    df["year"]      = df["date"].dt.year
    df["yearmonth"] = df["date"].dt.to_period("M")
    df["yearweek"]  = df["date"].dt.to_period("W")

    return df


def classify_size(persistence_days: int) -> str:
    """Classifies an active region by its persistence (days observed)."""
    if persistence_days <= THRESH_EPHEMERAL:
        return "ephemeral"
    if persistence_days < THRESH_LARGE:
        return "small"
    return "large"


# ---------------------------------------------------------------------------
# Aggregation
# ---------------------------------------------------------------------------

def aggregate_by_period(df: pd.DataFrame, period_col: str) -> pd.DataFrame:
    """
    Aggregates by period, avoiding double-counting of ARs with multiple
    daily observations. Uses each AR's peak complexity within the period.

    Output columns:
        period_col            - period (year / yearmonth / yearweek)
        n_total                - unique active regions in the period
        n_high_complexity      - ARs with peak complexity >= HIGH_COMPLEXITY
        complexity_area_sum    - sum of complexity * area (all daily obs.)
        n_large                - long-lived ARs (>= THRESH_LARGE days)
        n_small                - mid-lived ARs (2..THRESH_LARGE-1 days)
        n_ephemeral             - ephemeral ARs (<= THRESH_EPHEMERAL day)
    """
    rows = []

    for period, grp in df.groupby(period_col):
        
        ars = (
            grp.groupby("noaa_number")
            .agg(
                size_class   = ("size_class",   "first"),  
                peak_compl   = ("complexity",   "max"),    
                compl_x_area = ("compl_x_area", "sum"),    
            )
            .reset_index()
        )

        n_total     = len(ars)
        n_large     = int((ars["size_class"] == "large").sum())
        n_small     = int((ars["size_class"] == "small").sum())
        n_ephemeral = int((ars["size_class"] == "ephemeral").sum())
        n_high      = int((ars["peak_compl"] >= HIGH_COMPLEXITY).sum())

        
        ca_sum = float(round(ars["compl_x_area"].sum(), 2))

        rows.append({
            period_col:            period,
            "n_total":             n_total,
            "n_high_complexity":   n_high,
            "complexity_area_sum": ca_sum,
            "n_large":             n_large,
            "n_small":             n_small,
            "n_ephemeral":         n_ephemeral,
        })

    return pd.DataFrame(rows)


def reindex_to_full_range(
    result: pd.DataFrame,
    period_col: str,
    freq: str,
    start: str,
    end: str,
) -> pd.DataFrame:
    """
    Reindexes the DataFrame to the full range of periods between start and
    end. Periods with no AR at all (e.g. solar minima) are filled with:
      - counts → 0
      - sums   → 0.0
    """
    full_index = (
        pd.period_range(start=start, end=end, freq=freq)
        .astype(str)
        .tolist()
    )
    full_df = pd.DataFrame({period_col: full_index})

    result = result.copy()
    result[period_col] = result[period_col].astype(str)

    merged = full_df.merge(result, on=period_col, how="left")

    # Counts and sums → 0 where there is no data
    count_cols = ["n_total", "n_high_complexity", "n_large", "n_small",
                  "n_ephemeral", "complexity_area_sum"]
    for col in count_cols:
        if col in merged.columns:
            merged[col] = merged[col].fillna(0)

    # Integer dtype for counts
    int_cols = ["n_total", "n_high_complexity", "n_large", "n_small", "n_ephemeral"]
    for col in int_cols:
        if col in merged.columns:
            merged[col] = merged[col].astype(int)

    # Report filled-in periods
    filled = set(full_index) - set(result[period_col])
    if filled:
        print(f"  -> {len(filled)} period(s) with no ARs filled with 0:")
        print(f"     {sorted(filled)}")

    return merged


# ---------------------------------------------------------------------------
# Pipeline
# ---------------------------------------------------------------------------

def build_period_features(df: pd.DataFrame, start: str, end: str):
    """Builds and validates the annual / monthly / weekly features."""
    annual  = aggregate_by_period(df, "year")
    monthly = aggregate_by_period(df, "yearmonth")
    weekly  = aggregate_by_period(df, "yearweek")

    # Convert Period to string for clean serialization
    monthly["yearmonth"] = monthly["yearmonth"].astype(str)
    weekly["yearweek"]   = weekly["yearweek"].astype(str)

    # Reindex monthly and weekly to the full range to include periods with no ARs
    print("\nReindexing to the full date range...")
    monthly = reindex_to_full_range(monthly, "yearmonth", "M", start, end)
    weekly  = reindex_to_full_range(weekly,  "yearweek",  "W", start, end)

    # ---- Diagnostics: check consistency before saving ----
    print("=" * 65)
    print("DIAGNOSTICS — Annual dataset")
    print("=" * 65)
    print(annual.to_string(index=False))
    print()

    annual["_check"] = annual["n_large"] + annual["n_small"] + annual["n_ephemeral"]
    inconsistent = annual[annual["_check"] != annual["n_total"]]
    if inconsistent.empty:
        print("OK: class sum == n_total for every year")
    else:
        print("WARNING: inconsistencies found (n_large + n_small + n_ephemeral != n_total):")
        print(inconsistent[["year", "n_total", "n_large", "n_small", "n_ephemeral", "_check"]])
    annual.drop(columns=["_check"], inplace=True)

    return annual, monthly, weekly


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------

def main() -> None:
    parser = argparse.ArgumentParser(
        description="Builds annual/monthly/weekly Mount Wilson complexity "
                    "features from mount_wilson_dataset.csv"
    )
    parser.add_argument("--input", default=DEFAULT_CSV_IN,
                         help=f"Path to the input dataset (default: {DEFAULT_CSV_IN})")
    parser.add_argument("--start", default=DEFAULT_START_DATE,
                         help=f"Start of the reindexing range, YYYY-MM (default: {DEFAULT_START_DATE})")
    parser.add_argument("--end", default=DEFAULT_END_DATE,
                         help=f"End of the reindexing range, YYYY-MM (default: {DEFAULT_END_DATE})")
    parser.add_argument("--outdir", default=".",
                         help="Output directory for the generated CSV files (default: current directory)")
    args = parser.parse_args()

    outdir = Path(args.outdir)
    outdir.mkdir(parents=True, exist_ok=True)

    print(f"Loading dataset: {args.input}")
    df = load_dataset(args.input)
    print(f"Total records: {len(df)}")
    print(f"Date range: {df['date'].min().date()} to {df['date'].max().date()}")

    annual, monthly, weekly = build_period_features(df, args.start, args.end)

    # ---- Save — explicit quoting to avoid column-shifting issues ----
    annual.to_csv(
        outdir / "ar_features_annual.csv",
        index=False,
        quoting=csv.QUOTE_NONNUMERIC,   
        float_format="%.4f",            
    )
    monthly.to_csv(
        outdir / "ar_features_monthly.csv",
        index=False,
        quoting=csv.QUOTE_NONNUMERIC,
        float_format="%.4f",
    )
    weekly.to_csv(
        outdir / "ar_features_weekly.csv",
        index=False,
        quoting=csv.QUOTE_NONNUMERIC,
        float_format="%.4f",
    )

    print("=" * 65)
    print("FILES GENERATED")
    print("=" * 65)
    print(f"  ar_features_annual.csv  -> {len(annual)} rows")
    print(f"  ar_features_monthly.csv -> {len(monthly)} rows")
    print(f"  ar_features_weekly.csv  -> {len(weekly)} rows")
    print()
    print("Columns:", [c for c in monthly.columns if c != "yearmonth"])
    print()
    print("First 6 monthly rows:")
    print(monthly.head(6).to_string(index=False))


if __name__ == "__main__":
    main()
